#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#metrics_path:
#  path: /metrics
#  controller: App\Controller\MetricsController::index
#  methods: [GET]

tweede_golf_prometheus:
  resource: "@TweedeGolfPrometheusBundle/Resources/config/routing.yml"
  prefix: /