apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-php
  labels:
    app: {{ template "fullname" . }}-php
    component: php
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
  selector:
    app: {{ template "fullname" . }}-php
    component: php
    release: {{ .Release.Name }}
