apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: symvue
    component: web
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ template "fullname" . }}-web
    component: web
    release: {{ .Release.Name }}
