---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-web
  labels:
    app: {{ template "fullname" . }}-web
    component: web
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-web
      component: web
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "fullname" . }}-web
      labels:
        app: {{ template "fullname" . }}-web
        component: web
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.secret }}
      containers:
      - name: {{ .Chart.Name }}-web
        image: "{{ .Values.web.repository }}:{{ .Values.web.tag }}"
        ports:
          - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/
        resources:
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
            - key: site.conf
              path: site.conf
